# SPDX-FileCopyrightText: 2025 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

version: 2

builds:
  - flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.zst]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - AUTHORS.adoc
      - BUILD.adoc
      - CHANGELOG.adoc
      - CONTRIBUTING.adoc
      - LICENSES/*
      - README.md

checksum:
  name_template: "b2sums.txt"
  algorithm: blake2b

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
